tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/jvmmodel/TclJvmModelInferrer.xtend

Adding throws Exception to method signature of generated test methods.
This allows the fixture developers to throw exceptions in their code. SO they don't have to devlop an exception handling that causes the test to fail.

TE-313 Adding throws Exception for generated unit tests

---

updateHeaders.groovy

With this script we don't need to do this manually. We could also think about including this into the build process, so that we don't have to trigger the script manually.

simple script for updating copyright headers

---

aml/org.testeditor.aml.model/src/org/testeditor/aml/ModelUtil.xtend
rcp/org.testeditor.rcp4.views.teststepselection.tests/src/org/testeditor/rcp4/views/teststepselector/AmlModelTreeDropTextProviderTest.xtend
rcp/org.testeditor.rcp4.views.teststepselection/src/org/testeditor/rcp4/views/teststepselector/AmlModelTreeDropTextProvider.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/tests/AbstractTest.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/validation/TclMissingFixtureValidatorTest.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/jvmmodel/TclJvmModelInferrer.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/validation/TclValidator.xtend

* fix missing validation for unresolvable fixtures
* fix drag'n'drop from test step selector having "element" in template
string
* fix missing fixture instance var during generation

TE-372 minor fixes

---

aml/org.testeditor.aml.model/pom.xml
rcp/org.testeditor.rcp4.uatests/pom.xml
tcl/org.testeditor.tcl.model/pom.xml
tml/org.testeditor.tml.model/pom.xml
tsl/org.testeditor.tsl.model/pom.xml

Specifying `classPathLookupFilter` when using `xtext-maven-plugin` speeds up the build.
On my machine the build runs in 2:58 instead of 3:30 (without tests).
Also remove `<failOnValidationError>true</failOnValidationError>` as this is the default value and doesn't need to be specified.

Speed up build

---

Jenkinsfile

If a PR is merged before the release is completed we need to fetch from the remote before incrementing the develop version.

Improve release process

---

aml/org.testeditor.aml.dsl.tests/src/org/testeditor/aml/dsl/tests/formatter/AmlModelFormatterTest.xtend
aml/org.testeditor.aml.dsl.tests/src/org/testeditor/aml/dsl/tests/formatter/ComponentFormatterTest.xtend
aml/org.testeditor.aml.dsl/src/org/testeditor/aml/dsl/formatting2/AmlFormatter.xtend

This fixes the formatting for the import section and components.

TE-396 aml pretty print

---

Jenkinsfile

Sometimes we want to build the product on feature branches as well (for example when we change the project structure).
With this change we can add `-with-product` to a branch name if we want the product to be built on this branch.

Allow building the product on feature branches

---

.gitignore
common/org.testeditor.dsl.common.testing/META-INF/MANIFEST.MF
tcl/org.testeditor.tcl.dsl/META-INF/MANIFEST.MF

After upgrading to new eclipse neon, some workspace issues popped up 
* exporting plugins failed because of circular dependencies
* text files were generated by emf-plugin

remove unused dependency, ignore emf-generated txt

---

common/org.testeditor.dsl.common.testing/src/org/testeditor/dsl/common/testing/DummyFixture.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/jvmmodel/SimpleTclGeneratorIntegrationTest.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/tests/formatter/TclModelFormatterTest.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/tests/parser/TclModelParserTest.xtend
tcl/org.testeditor.tcl.dsl.ui.tests/src/org/testeditor/tcl/dsl/ui/tests/contentassist/TclTestCaseContentAssistTest.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/Tcl.xtext
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/formatting2/TclFormatter.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/jvmmodel/TclJvmModelInferrer.xtend
tcl/org.testeditor.tcl.model/model/tcl.xcore

Support a test setup and cleanup for the test-cases. This is part 1, reusing such definitions by multiple tests is not yet implemented.

TE-402 support test setup and cleanup part 1

---

rcp/org.testeditor.rcp4.uatests/src/main/java/org/testeditor/fixture/swt/SWTFixture.java
rcp/org.testeditor.rcp4.uatests/src/test/java/org/testeditor/rcp4/createprojects/CreateWebProjectWithExampleTest.tcl
rcp/org.testeditor.rcp4.uatests/src/test/java/org/testeditor/rcp4/swt.aml
rcp/org.testeditor.rcp4.uatests/src/test/java/org/testeditor/rcp4/testeditor.aml

Running the `uatests` on Windows fails as the `CreateWebProjectWithExampleTest` is not finished by the time the next test runs. This is because the test does not wait for the progress dialog to finish and so the next running test cannot clean the workspace.

TE-405 Improve existing tests by waiting for the "Progress Information" dialog to vanish

---

common/org.testeditor.dsl.common.ui/META-INF/MANIFEST.MF
common/org.testeditor.dsl.common.ui/src/org/testeditor/dsl/common/ui/workbench/PartHelper.xtend
rcp/org.testeditor.rcp4.views.tcltestrun/src/org/testeditor/rcp4/views/tcltestrun/TclLauncherUi.xtend

After the test execution the result view (JUnit view) should be made visible.
Note that I tried using e4 mechanisms but the `EPartService` was very unhelpful as it complained about the non active workbench window. The workbench window is not active at this point, but we can use an existing one (which is not active) to open the view.

TE-405 activate JUnit result view after test execution

---

tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/validation/FileExtensionValidator.xtend

FileExtensionValidator should not inherit from `XbaseValidator` - otherwise it performs all the standard Xbase checks as well.

get rid of import warnings

---

rcp/org.testeditor.rcp4.product/testeditor.product

This gives us a few benefits with the type handling (i.e. navigate from a generated Java file to the TCL).

add missing bundle org.eclipse.xtext.common.types.shared to the product

---

tcl/org.testeditor.tcl.dsl.ui/src/org/testeditor/tcl/dsl/ui/contentassist/TclProposalProvider.xtend

`currentNode.nextSibling` might be null if we're on the end of the document

TE-417 fix NPE in TclProposalProvider

---

common/org.testeditor.dsl.common.testing/src/org/testeditor/dsl/common/testing/AssertionHelper.xtend
common/org.testeditor.dsl.common.testing/src/org/testeditor/dsl/common/testing/DummyFixture.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/jvmmodel/SimpleTclGeneratorIntegrationTest.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/tests/formatter/TestStepFormatterTest.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/tests/parser/TclModelParserTest.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/util/TclModelUtilTest.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/Tcl.xtext
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/formatting2/TclFormatter.xtend
tcl/org.testeditor.tcl.model/model/tcl.xcore
tcl/org.testeditor.tcl.model/src/org/testeditor/tcl/util/TclModelUtil.xtend

I ran into a small problem with the formatter as there is an Xtext bug (have filed it and added a TODO to the code). Formatting of the punctuation will currently not work in the editor.

TE-438 allow question mark in TCL grammar

---

releng/org.testeditor.releng.parent/pom.xml

Apparently the application of the `maven-source-plugin` kills the Tycho product build...

Fix build (remove maven-source-plugin)

---

common/org.testeditor.dsl.common.ui/src/org/testeditor/dsl/common/ui/utils/ProjectContentGenerator.xtend
common/org.testeditor.dsl.common/src/org/testeditor/dsl/common/util/classpath/ClasspathUtil.xtend

* add standard source class paths for gradle projects, regardless of generated examples
* add proxy settings to gradle project
* add forced module version to gradle project (for selenium)

TE-479 correct gradle project generation

---

.gitignore
common/org.testeditor.dsl.common.ui/src/org/testeditor/dsl/common/ui/utils/ProjectContentGenerator.xtend

* gitignore logs produced during test runs
* adjust eclipse build path when creating example projects

TE-489 adjust eclipse build path for example projects due to gradle upgrade

---

tcl/org.testeditor.tcl.dsl.ide/src/org/testeditor/tcl/dsl/ide/highlighting/TclSemanticHighlightingCalculator.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/tests/TclModelGenerator.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/tests/parser/TclModelParserTest.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/validation/TclParameterUsageValidatorTest.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/validation/TclVarUsageValidatorTest.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/util/TclModelUtilTest.xtend
tcl/org.testeditor.tcl.dsl.ui/src/org/testeditor/tcl/dsl/ui/editor/DropUtils.xtend
tcl/org.testeditor.tcl.dsl.ui/src/org/testeditor/tcl/dsl/ui/navigation/TclHyperLinkHelper.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/Tcl.xtext
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/formatting2/TclFormatter.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/validation/TclTypeValidationUtil.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/validation/TclValidator.xtend
tcl/org.testeditor.tcl.model/model/tcl.xcore
tcl/org.testeditor.tcl.model/src/org/testeditor/tcl/util/TclModelUtil.xtend

The introduction of the class `FixtureReference` made the code more complex without any benefits and also broke the UI navigation from test steps to their AML templates (`TclHyperLinkHelper`).

Revert FixtureReference refactoring

---

common/org.testeditor.dsl.common/src/org/testeditor/dsl/common/util/classpath/ClasspathUtil.xtend
rcp/org.testeditor.rcp4.views.projectexplorer/plugin.xml
rcp/org.testeditor.rcp4.views.tcltestrun.tests/src/org/testeditor/rcp4/views/tcltestrun/TclLauncherUiTest.xtend
rcp/org.testeditor.rcp4.views.tcltestrun/src/org/testeditor/rcp4/views/tcltestrun/TclLauncherUi.xtend
tcl/org.testeditor.tcl.dsl.ui/src/org/testeditor/tcl/dsl/ui/util/TclIndexHelper.xtend
tsl/org.testeditor.tsl.dsl.ui/src/org/testeditor/tsl/dsl/ui/wizard/NewTslFileWizard.xtend

* ClasspathUtil: test on uri scheme to check if element is eclipse resolved
* TclLauncherUITest: documentation and added test and made private create methods actually private
* TclLanucherUI: reduce warnings, included package derivation (which was missing), build tslIndex only if actually using a tsl in the selection, allow tsl execution for gradle projects, too
* TclIndexHelper: changed ArrayList -> List in signature, added classpathUriContext to allow resolving org.junit.Test during resolving (and thereby generating) TestCase eObjects

TE-492 fix exception during test selection

---

tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/jvmmodel/TclExpressionBuilderTest.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/jvmmodel/TclJvmTypeReferenceUtilTest.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/jvmmodel/TypeExpressionComputerTest.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/validation/TclVarUsageValidatorTest.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/jvmmodel/SimpleTypeComputer.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/jvmmodel/TclAssertCallBuilder.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/jvmmodel/TclExpressionBuilder.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/jvmmodel/TclExpressionTypeComputer.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/jvmmodel/TclJvmModelInferrer.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/validation/TclValidator.xtend

- refactor  JvmTypeReference parameters to Optional<..>
- rename class under test to typeRefenceUtil in TclJvmTypeReferenceUtilTest
- refactor TclJvmModelInferer.toParameterString
no semantic changes

refactorizations in prepartion enum parameters

---

tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/jvmmodel/CallTreeBuilderTest.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/jvmmodel/SimpleTclGeneratorIntegrationTest.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/jvmmodel/TclParameterGeneratorIntegrationTest.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/jvmmodel/macro/MacroGeneratorIntegrationTest.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/jvmmodel/CallTreeBuilder.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/jvmmodel/TclJvmModelInferrer.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/messages/TclElementStringifier.xtend

* extracted some code from `TclJvmModelInferrer` for building log entry strings from test steps and other TCL model elements, and put it into the utility class, `TclElementStringifier`, along with other methods for "stringification"
* `CallTreeBuilder` should now handle test steps in both component and macro context, and resolve macro and fixture calls.
Left to do:
* handling configs
* complex test with non-trivial setup, cleanup, and test steps
* test nested macro calls (e.g. macro calls macro calls fixture method)

handle different test step types in CallTreeBuilder

---

.travis.yml

publishing after tagging does not work for plugins, since it is executed after compileFeature (which should not run when publishing).

put target platform compile in a separate stage
