core/org.testeditor.aml.dsl.tests/src/org/testeditor/aml/dsl/scoping/InteractionScopingTest.xtend
core/org.testeditor.aml.dsl.tests/src/org/testeditor/aml/dsl/scoping/SimpleImportScopingTest.xtend
core/org.testeditor.aml.dsl.tests/src/org/testeditor/fixture/core/interaction/FixtureMethod.java
core/org.testeditor.aml.dsl/src/org/testeditor/aml/dsl/Aml.xtext
core/org.testeditor.aml.dsl/src/org/testeditor/aml/dsl/AmlRuntimeModule.java
core/org.testeditor.aml.dsl/src/org/testeditor/aml/dsl/GenerateAml.mwe2
core/org.testeditor.aml.dsl/src/org/testeditor/aml/dsl/naming/AmlQualifiedNameProvider.xtend
core/org.testeditor.aml.dsl/src/org/testeditor/aml/dsl/scoping/AmlDelegateScopeProvider.xtend
core/org.testeditor.aml.dsl/src/org/testeditor/aml/dsl/scoping/AmlScopeProvider.xtend
core/org.testeditor.aml.dsl/src/org/testeditor/aml/dsl/scoping/MethodReferenceScopes.xtend
core/org.testeditor.aml.model/model/aml.xcore

[TE-245] AML support model and Java imports

---

pom.xml
wsdl/org.testeditor.aml.wsdl.feature/.project
wsdl/org.testeditor.aml.wsdl.feature/build.properties
wsdl/org.testeditor.aml.wsdl.feature/feature.xml
wsdl/org.testeditor.aml.wsdl.feature/pom.xml
wsdl/org.testeditor.aml.wsdl.importer.ui/.classpath
wsdl/org.testeditor.aml.wsdl.importer.ui/.project
wsdl/org.testeditor.aml.wsdl.importer.ui/.settings/org.eclipse.jdt.core.prefs
wsdl/org.testeditor.aml.wsdl.importer.ui/META-INF/MANIFEST.MF
wsdl/org.testeditor.aml.wsdl.importer.ui/build.properties
wsdl/org.testeditor.aml.wsdl.importer.ui/pom.xml

please don't merge this right now, just for demo

[TE-273] initial project setup

---

aml/org.testeditor.aml.dsl.tests/src/org/testeditor/aml/dsl/tests/parser/ValueSpaceParserTest.xtend
aml/org.testeditor.aml.dsl.tests/src/org/testeditor/aml/dsl/tests/parser/validation/ValidationTest.xtend
aml/org.testeditor.aml.dsl/resources/messages.properties
aml/org.testeditor.aml.dsl/src/org/testeditor/aml/dsl/Aml.xtext
aml/org.testeditor.aml.dsl/src/org/testeditor/aml/dsl/Messages.java
aml/org.testeditor.aml.dsl/src/org/testeditor/aml/dsl/validation/AmlValidator.xtend
aml/org.testeditor.aml.model/model/aml.xcore

This adds support for regular expressions to AML.

Support regular expressions in AML

---

rcp/org.testeditor.rcp4.product/src/org/testeditor/rcp4/product/NavFilter.xtend
rcp/org.testeditor.rcp4.uatests/.classpath
rcp/org.testeditor.rcp4.uatests/pom.xml

- Change Filter to hide compile unit
- fixing missing .classpath
- format code of pom.xml

TE-317 Show src folder in project explorer but still hide java src

---

rcp/org.testeditor.rcp4.views.projectexplorer/pom.xml
rcp/pom.xml

- Adding new bundle to maven build

TE-329 TE specific Test Explorer

---

tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/jvmmodel/TclJvmModelInferrer.xtend

This improves the traceability of the generated code by providing trace information during code generation.

Use ITreeAppendable for code generation

---

rcp/org.testeditor.rcp4.views.teststepselection/src/org/testeditor/rcp4/views/teststepselector/TestStepSelector.xtend

- Register on editor activation event a refreh

TE-343 Refresh TeststepSelector on editor content change

---

aml/org.testeditor.aml.model/model/aml.xcore
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/validation/TclValidatorTest.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/validation/TclValidator.xtend
tcl/org.testeditor.tcl.model/src/org/testeditor/tcl/util/TclModelUtil.xtend

Need some help for this implementation. It works but i need to make a type cast to the StringLiteralsImpl. On the model interface i didn't find any way to get the values.
* Adding lookup method to get value space from test step variable
* Adding validate method for StepContentVaraible

TE-344 Validate ValueSpace restriction

---

common/org.testeditor.dsl.common.ui/src/org/testeditor/dsl/common/ui/wizards/NewProjectWizard.xtend

* exclude "target" from eclipse resources in new project wizard

TE-339 remove duplicate entries from test step sel

---

rcp/org.testeditor.rcp4.uatests/src/main/java/org/testeditor/rcp4/createprojects/CreateWebProjectWithExampleTest.tcl
rcp/org.testeditor.rcp4.uatests/src/main/java/org/testeditor/rcp4/testeditor.aml
rcp/org.testeditor.rcp4.views.projectexplorer/fragment.e4xmi
rcp/org.testeditor.rcp4/Application.e4xmi

- change identifier in aml
- wait step to ensure leaving of dialog

TE-358 Fixing test problem with replaced project explorer

---

rcp/org.testeditor.rcp4.uatests/.classpath
rcp/org.testeditor.rcp4.uatests/META-INF/MANIFEST.MF
rcp/org.testeditor.rcp4.uatests/build.properties
rcp/org.testeditor.rcp4.uatests/lib/.gitignore
rcp/org.testeditor.rcp4.uatests/pom.xml

set core fixture to version 2.5.2 and add "lib/" folder to the maven-clean-plugin

Improve build of uatests

---

aml/org.testeditor.aml.dsl.tests/src/org/testeditor/aml/dsl/tests/AbstractTest.xtend
aml/org.testeditor.aml.dsl.tests/src/org/testeditor/aml/dsl/tests/parser/InteractionTypeParserTest.xtend
aml/org.testeditor.aml.dsl/src/org/testeditor/aml/dsl/Aml.xtext
common/org.testeditor.dsl.common.testing/META-INF/MANIFEST.MF
common/org.testeditor.dsl.common.testing/src/org/testeditor/dsl/common/testing/XtextAssertionHelper.xtend

It should be possible to reference more than two parameters.

Fix AML grammar

---

README.md
releng/org.testeditor.releng.parent/pom.xml

This change fixes the Jacoco configuration and the link in the readme file.

TE-375 fix jacoco config

---

tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/validation/TclMissingFixtureValidatorTest.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/validation/TclValidator.xtend

TE-378 No resolution info asertion test step.

---

common/org.testeditor.dsl.common.ui/src/org/testeditor/dsl/common/ui/utils/ProgressMonitorRunner.xtend
rcp/org.testeditor.rcp4.tcltestrun/src/org/testeditor/rcp4/tcltestrun/MavenExecutor.java
rcp/org.testeditor.rcp4.tcltestrun/src/org/testeditor/rcp4/tcltestrun/TclMavenLauncher.xtend

- Maven process is cancable
- Gradle tooling api doesn't support build cancel opration at the
current version:
https://docs.gradle.org/current/userguide/embedding.html

Cancel Operation on maven test execution

---

Jenkinsfile

We don't want to deploy the product to our Maven repo on Bintray.

Build the product in a separate stage

---

tcl/org.testeditor.tcl.dsl.ide/src/org/testeditor/tcl/dsl/ide/highlighting/TclSemanticHighlightingCalculator.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/jvmmodel/AbstractTclGeneratorIntegrationTest.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/scoping/integration/TclGenerationOfLocatorStrategyTests.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/tests/TclCallParameterTest.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/tests/TclModelGenerator.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/tests/formatter/TclModelFormatterTest.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/tests/parser/TclModelParserTest.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/validation/TclModelContentValidator.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/validation/TclParameterUsageValidatorTest.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/validation/TclVarUsageValidatorTest.xtend
tcl/org.testeditor.tcl.dsl.ui/src/org/testeditor/tcl/dsl/ui/highlighting/TclHighlightingConfiguration.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/Tcl.xtext
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/formatting2/TclFormatter.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/naming/TclQualifiedNameProvider.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/validation/TclValidator.xtend
tcl/org.testeditor.tcl.model/model/tcl.xcore

- move name back to TestCase and MacroCollection
- improve formatter
- remove unused import and .gitkeep

Move name back to TestCase and MacroCollection + further cleanup

---

rcp/org.testeditor.rcp4/src/org/testeditor/rcp4/ApplicationActionBarAdvisor.xtend
rcp/org.testeditor.rcp4/src/org/testeditor/rcp4/ApplicationWorkbenchWindowAdvisor.xtend

- adding menu structure to e3 action bar advisor
- remove unwanted menut items

Fixing e4 model problem with menu on second start

---

rcp/org.testeditor.rcp4.views.tcltestrun/src/org/testeditor/rcp4/views/tcltestrun/TclLauncherUi.xtend
rcp/org.testeditor.rcp4.views.tcltestrun/src/org/testeditor/rcp4/views/tcltestrun/TestResultFileWriter.xtend

- fixing file directory creation
- fixing npe

TE-404 User Feedback on test execution failure

---

common/org.testeditor.dsl.common.ui.tests/META-INF/MANIFEST.MF
common/org.testeditor.dsl.common.ui.tests/src/org/testeditor/dsl/common/ui/utils/ProjectContentGeneratorTest.xtend
common/org.testeditor.dsl.common.ui/META-INF/MANIFEST.MF
common/org.testeditor.dsl.common.ui/src/org/testeditor/dsl/common/ui/gradle/GradleHelper.xtend
common/org.testeditor.dsl.common.ui/src/org/testeditor/dsl/common/ui/utils/ProjectContentGenerator.xtend
rcp/org.testeditor.rcp4.tcltestrun/src/org/testeditor/rcp4/tcltestrun/LaunchResult.xtend
rcp/org.testeditor.rcp4.tcltestrun/src/org/testeditor/rcp4/tcltestrun/TclGradleLauncher.xtend
rcp/org.testeditor.rcp4.tcltestrun/src/org/testeditor/rcp4/tcltestrun/TclLauncher.xtend
rcp/org.testeditor.rcp4.tcltestrun/src/org/testeditor/rcp4/tcltestrun/TclMavenLauncher.xtend

Improves the code that launches Gradle builds and removes `returnCode` from `LaunchResult`.

improve gradle launch code

---

common/org.testeditor.dsl.common.ui.tests/src/org/testeditor/dsl/common/ui/utils/ProjectContentGeneratorTest.xtend
common/org.testeditor.dsl.common.ui/src/org/testeditor/dsl/common/ui/gradle/GradleHelper.xtend
common/org.testeditor.dsl.common.ui/src/org/testeditor/dsl/common/ui/utils/ProjectContentGenerator.xtend
common/org.testeditor.dsl.common.ui/src/org/testeditor/dsl/common/ui/wizards/NewProjectWizard.xtend
common/org.testeditor.dsl.common.ui/src/org/testeditor/dsl/common/ui/wizards/SwingDemoContentGenerator.xtend

Depends on #122 (please merge this first).
This change improves the project generator (still not good enough) - but generates the Swing demo.

TE-405 improve project generator

---

rcp/org.testeditor.rcp4/src/org/testeditor/rcp4/ApplicationWorkbenchAdvisor.xtend

- Change image extension from gif to png for project, error and task

TE-407 Fix missing project icons

---

tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/validation/TclValidatorTest.xtend
tcl/org.testeditor.tcl.model/src/org/testeditor/tcl/util/TclModelUtil.xtend

- adding missing copyright
- Testcase to verify selection of correct valuespace
- identify component element with locator

TE-408 Correct value space validation

---

rcp/org.testeditor.rcp4/src/org/testeditor/rcp4/dialogs/NetworkConnectionSettingDialog.java

- Set proxy data to proxy service

Bugfix Eclipse Proxy settings

---

tcl/org.testeditor.tcl.dsl.ide/src/org/testeditor/tcl/dsl/ide/highlighting/TclSemanticHighlightingCalculator.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/jvmmodel/MacroCallVariableResolver.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/jvmmodel/TclAssertCallBuilder.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/jvmmodel/TclExpressionBuilder.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/jvmmodel/VariableResolver.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/messages/TclSyntaxErrorMessageProvider.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/scoping/TclDelegateScopeProvider.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/validation/FileExtensionValidator.xtend

* Remove dead variable
* Organize imports
* Fix missing Copyright

Improvement Code cleanup

---

common/org.testeditor.dsl.common.tests/src/org/testeditor/dsl/common/util/classpath/ClasspathUtilTest.xtend
common/org.testeditor.dsl.common.tests/src/org/testeditor/dsl/common/util/classpath/GradleClasspathUtilTest.xtend
common/org.testeditor.dsl.common.tests/src/org/testeditor/dsl/common/util/classpath/GradleServerConnectUtil.xtend

- Assume tests can reach the gradle server

Skipping tests behind a proxy

---

rcp/org.testeditor.rcp4.uatests/src/main/java/org/testeditor/fixture/swt/SWTFixture.java
rcp/org.testeditor.rcp4.uatests/src/main/java/org/testeditor/fixture/swt/TestEditorFixture.java
rcp/org.testeditor.rcp4.uatests/src/test/java/org/testeditor/rcp4/writetests/WriteSimpleTestWithoutPackageTest.tcl

* change fixture api to boolean

Improvement using boolean instead of string compare

---

aml/org.testeditor.aml.dsl.ui/templates/templates.xml
rcp/org.testeditor.rcp4.uatests/src/main/java/org/testeditor/fixture/swt/SWTFixture.java
rcp/org.testeditor.rcp4.uatests/src/main/java/org/testeditor/fixture/swt/swt.aml
rcp/org.testeditor.rcp4.uatests/src/main/java/org/testeditor/fixture/swt/testeditor.aml
rcp/org.testeditor.rcp4.uatests/src/test/java/org/testeditor/rcp4/writetests/AmlTemplateTest.tcl

Wanted to write some "uatests" but can't get them to run on my machine.

TE-423 improve aml completion

---

common/org.testeditor.dsl.common/src/org/testeditor/dsl/common/util/classpath/MavenClasspathUtil.xtend
rcp/org.testeditor.rcp4.uatests/src/main/java/org/testeditor/fixture/swt/testeditor.aml

- Using allways SWTLocatorStrategy
- Enable Caching of classpath infromation in maven to avoid multiple effective_pom calls

TE-369 use SWTLocatorStrategy and fix caching of clsspath informaiton at

---

rcp/org.testeditor.rcp4.uatests/src/main/java/org/testeditor/fixture/eclipse/EclipseWorkbenchFixture.aml
rcp/org.testeditor.rcp4.uatests/src/main/java/org/testeditor/fixture/eclipse/EclipseWorkbenchFixture.java
rcp/org.testeditor.rcp4.uatests/src/main/java/org/testeditor/fixture/swt/SWTFixture.java
rcp/org.testeditor.rcp4.uatests/src/test/java/org/testeditor/rcp4/TestEditorConfig.config

Improve the test stability by closing all editors after tests and wait

---

aml/org.testeditor.aml.model/model/aml.xcore
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/jvmmodel/AbstractTclGeneratorIntegrationTest.xtend
tcl/org.testeditor.tcl.dsl.tests/src/org/testeditor/tcl/dsl/jvmmodel/SimpleTclGeneratorIntegrationTest.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/jvmmodel/TclAssertCallBuilder.xtend
tcl/org.testeditor.tcl.model/model/tcl.xcore
tcl/org.testeditor.tcl.model/src/org/testeditor/tcl/util/TclModelUtil.xtend

This change includes some refactorings and cleanups only, no semantics changed.

TE-439 refactorings only

---

tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/Tcl.xtext
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/jvmmodel/TclAssertCallBuilder.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/jvmmodel/TclExpressionBuilder.xtend
tcl/org.testeditor.tcl.model/model/tcl.xcore

corrected a typo that I introduced a long time ago ...

TE-440 rename ...Then to ...Than

---

rcp/org.testeditor.rcp4.uatests/.classpath
rcp/org.testeditor.rcp4.uatests/src/main/java/org/testeditor/fixture/eclipse/EclipseWorkbenchFixture.aml
rcp/org.testeditor.rcp4.uatests/src/main/java/org/testeditor/fixture/swt/SWTFixture.java
rcp/org.testeditor.rcp4.uatests/src/main/java/org/testeditor/fixture/swt/swt.aml
rcp/org.testeditor.rcp4.uatests/src/test/java/org/testeditor/rcp4/SampleProjects.tml
rcp/org.testeditor.rcp4.uatests/src/test/java/org/testeditor/rcp4/createprojects/CreateSimpleTestEditorProjectFromContextMenuWithNewWizardTest.tcl
rcp/org.testeditor.rcp4.uatests/src/test/java/org/testeditor/rcp4/createprojects/CreateSwingDemoAndRunTest.tcl
rcp/org.testeditor.rcp4.uatests/src/test/java/org/testeditor/rcp4/createprojects/CreateWebProjectWithExampleTest.tcl
rcp/org.testeditor.rcp4.uatests/src/test/java/org/testeditor/rcp4/writetests/AmlTemplateTest.tcl
rcp/org.testeditor.rcp4.uatests/src/test/java/org/testeditor/rcp4/writetests/WriteSimpleTestWithoutPackageTest.tcl

make sure to wait a couple of seconds before deciding that dialog "Progress Information" doesn't show up!

TE-441 fix some uatests test problems

---

README.md
build.gradle

Update Readme and setup an ambrella for prepare web views in build

Adding web build to readme and create a ambrella web build step

---

Jenkinsfile
rcp/org.testeditor.rcp4.views.tcltestrun/META-INF/MANIFEST.MF
rcp/org.testeditor.rcp4.views.tcltestrun/build.properties

Include webapp in bundle and extract bundle after deployment

---

aml/org.testeditor.aml.dsl.tests/src/org/testeditor/aml/dsl/scoping/InteractionScopingTest.xtend
aml/org.testeditor.aml.dsl.tests/src/org/testeditor/aml/dsl/scoping/ValueSpaceAssignmentScopingTest.xtend
aml/org.testeditor.aml.dsl.tests/src/org/testeditor/aml/dsl/tests/formatter/ValueSpaceAssignmentFormatterTest.xtend
aml/org.testeditor.aml.dsl.tests/src/org/testeditor/aml/dsl/tests/parser/ComponentElementParserTest.xtend
aml/org.testeditor.aml.dsl/src/org/testeditor/aml/dsl/Aml.xtext
aml/org.testeditor.aml.dsl/src/org/testeditor/aml/dsl/formatting2/AmlFormatter.xtend
aml/org.testeditor.aml.dsl/src/org/testeditor/aml/dsl/scoping/AmlScopeProvider.xtend
aml/org.testeditor.aml.dsl/src/org/testeditor/aml/dsl/validation/AmlValidator.xtend
aml/org.testeditor.aml.model/model/aml.xcore
aml/org.testeditor.aml.model/src/org/testeditor/aml/ModelUtil.xtend

depends on https://github.com/test-editor/test-editor-xtext/pull/232
please merge this one first and update this branch afterwards

TE-454 value space restriction formatting

---

docs/I18n_AML.md

Please read the draft and comment. You can use the "View" button so see the rendered HTML which is easier to read.

first draft for i18n AML

---

common/org.testeditor.dsl.common.testing/src/org/testeditor/dsl/common/testing/DslParseHelper.xtend
tcl/org.testeditor.tcl.dsl.ui.tests/src/org/testeditor/tcl/dsl/ui/tests/editor/AbstractTclModelDragAndDropUpdaterTest.xtend
tcl/org.testeditor.tcl.dsl.ui.tests/src/org/testeditor/tcl/dsl/ui/tests/editor/TclModelDragAndDropUpdaterIntegrationTest.xtend

TE-455 refactor tests

---

rcp/org.testeditor.rcp4/src/org/testeditor/rcp4/dialogs/NetworkConnectionSettingDialog.java

Adding tooltip to network connection dialog

---

Jenkinsfile
build.gradle
rcp/org.testeditor.web.testexecutionlogview/app/logGroupView.component.ts
rcp/org.testeditor.web.testexecutionlogview/app/testRunView.component.ts
rcp/org.testeditor.web.testexecutionlogview/index.html

Small cleanups of web component

Cleanup unused code

---

rcp/org.testeditor.rcp4.uatests/META-INF/MANIFEST.MF
rcp/org.testeditor.rcp4.views.tcltestrun.tests/src/org/testeditor/rcp4/views/tcltestrun/TclLauncherUiTest.xtend
rcp/org.testeditor.rcp4.views.tcltestrun/src/org/testeditor/rcp4/views/tcltestrun/TclLauncherUi.xtend
rcp/org.testeditor.rcp4/src/org/testeditor/rcp4/ApplicationWorkbenchWindowAdvisor.xtend

Using Eclipse job api to exeucte tests.
Showing user dialog which can be switched to the background

TE-461 Run tests optional in background

---

rcp/org.testeditor.rcp4.views.tcltestrun/src/org/testeditor/rcp4/views/tcltestrun/model/TestExecutionManager.xtend
rcp/org.testeditor.rcp4.views.tcltestrun/src/org/testeditor/rcp4/views/tcltestrun/rest/TestExecutionLogService.xtend
rcp/org.testeditor.web.testexecutionlogview/app/testExecList.components.html

showing aborted test execution in the logview

bugfix hanlde aborted tests

---

rcp/org.testeditor.web.testexecutionlogview/loginTestPage.html

This file is added into the web Test Execution Log path to serve this site over jetty.
So during testexecution this File can be accessed through the teststep 'Browse to "http://127.0.0.1:19091/testlogs/web-app/loginTestPage.html"'

[TE-477] To browse a local file in the Test-Editor 2

---

web/backend/src/integrationTest/resources/test-config.yml
web/backend/src/main/resources/META-INF/beans.xml

minor configurations that were not changed

clean up web project

---

rcp/org.testeditor.rcp4.uatests/src/test/java/org/testeditor/rcp4/createprojects/CreateSwingDemoAndRunTest.tcl

works on the (old) platform with more memory

reactivate swing demo run test

---

tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/jvmmodel/TclJvmModelInferrer.xtend
tcl/org.testeditor.tcl.dsl/src/org/testeditor/tcl/dsl/jvmmodel/TestRunReporterGenerator.xtend

separate append from code/text generation

refactor TestRunReporterGenerator

---

rcp/org.testeditor.rcp4.product/testeditor.product
target-platform/org.testeditor.releng.target.parent/pom.xml

tested to allow plugin installation within eclipse

upgrade to oxygen 3a

---

releng/org.testeditor.releng.parent/pom.xml

fixes a build problem I had on my mac but it seems to be a general problem see the given issue

fix a build problem
